<?php
/**
 * Plugin Name: FCMC Households
 * Description: The club's membership roster as records independent of WordPress user
 *              accounts. A household is one membership: up to two people and any number
 *              of cars. It exists whether or not anyone has registered on the site, which
 *              is what lets the 2026 roster be imported without creating 43 accounts
 *              nobody asked for. A user account attaches later, by email.
 *
 *              Capability type: its OWN ('fcmc_household' / 'fcmc_households'), not the
 *              default `post`, and NOT mapped onto `fcmc_manage_members`. That mapping was
 *              tried and reverted — see .superpowers/sdd/2026-09-11-fcmc-roster-import/
 *              task-2-report.md. WordPress's _post_type_meta_capabilities() registers
 *              whatever string a post type maps `edit_post`/`read_post`/`delete_post` to as
 *              a META capability in the global $post_type_meta_caps array. Mapping those to
 *              `fcmc_manage_members` made WordPress believe THAT STRING was a meta
 *              capability, so every bare (no-post-ID) `current_user_can('fcmc_manage_members')`
 *              call got intercepted by map_meta_cap()'s default branch, re-mapped to
 *              `edit_post` with no post to check, and resolved to `do_not_allow` — silently
 *              breaking the officer-facing Club Roster tab, which gates on exactly that bare
 *              call. A post type's meta caps must never be mapped onto a standalone
 *              capability string used elsewhere as a plain gate.
 *
 *              `fcmc_manage_members` remains an ordinary, unmapped capability (see
 *              fcmc-roster.php); the primitives generated by `capability_type` below
 *              (edit_fcmc_households, delete_fcmc_households, etc.) are granted directly to
 *              `membership_officer` and `administrator` in fcmc_roster_install().
 *
 * @see docs/superpowers/specs/2026-09-10-fcmc-roster-import-design.md
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'init', function () {
	register_post_type( 'fcmc_household', array(
		'label'           => __( 'Households', 'fcmc' ),
		'public'          => false,          // never a front-end URL — this is member PII
		'show_ui'         => true,
		'show_in_menu'    => true,
		'menu_icon'       => 'dashicons-groups',
		'capability_type' => array( 'fcmc_household', 'fcmc_households' ),
		'capabilities'    => array( 'create_posts' => 'do_not_allow' ), // created by import or signup only
		'map_meta_cap'    => true,
		'supports'        => array( 'title' ),
		'show_in_rest'    => false,          // keep it off the public REST surface
	) );
} );

/**
 * Normalize an email for comparison. One rule, used everywhere.
 *
 * @param string $email Raw email.
 * @return string
 */
function fcmc_normalize_email( $email ) {
	return strtolower( trim( (string) $email ) );
}

/**
 * Find an UNCLAIMED household by either member's email.
 *
 * @param string $email Email to match.
 * @return int|null Post ID, or null.
 */
function fcmc_household_find_by_email( $email ) {
	$email = fcmc_normalize_email( $email );
	if ( '' === $email ) {
		return null;
	}

	foreach ( fcmc_household_all() as $id ) {
		if ( get_post_meta( $id, 'claimed_by', true ) ) {
			continue;
		}
		foreach ( array( 'member1_email', 'member2_email' ) as $key ) {
			if ( fcmc_normalize_email( get_post_meta( $id, $key, true ) ) === $email ) {
				return (int) $id;
			}
		}
	}

	return null;
}

/**
 * All household IDs. ~48 records, so a plain query is fine.
 *
 * @param array $args Extra WP_Query args.
 * @return int[]
 */
function fcmc_household_all( $args = array() ) {
	return get_posts( array_merge( array(
		'post_type'      => 'fcmc_household',
		'post_status'    => 'publish',
		'posts_per_page' => -1,
		'fields'         => 'ids',
		'orderby'        => 'title',
		'order'          => 'ASC',
	), $args ) );
}

/**
 * A household as a flat array, with every meta key present.
 *
 * @param int $id Post ID.
 * @return array
 */
function fcmc_household_get( $id ) {
	$keys = array(
		'member1_name', 'member1_phone', 'member1_email',
		'member2_name', 'member2_phone', 'member2_email',
		'address', 'city', 'state', 'zip',
		'cars', 'paid_through', 'member_since',
		'fcmc_source', 'claimed_by', 'import_batch',
	);

	$out = array( 'id' => (int) $id );
	foreach ( $keys as $key ) {
		$out[ $key ] = get_post_meta( $id, $key, true );
	}
	$out['cars'] = is_array( $out['cars'] ) ? $out['cars'] : array();

	return $out;
}

/**
 * Attach a user account to a household and adopt its membership facts.
 *
 * The imported date lands in fcmc_paid_through_manual — the BASELINE, not the
 * effective date — so recompute treats it as a floor and can never wipe it.
 *
 * @param int $household_id Household post ID.
 * @param int $user_id      User ID.
 */
function fcmc_household_claim( $household_id, $user_id ) {
	$h = fcmc_household_get( $household_id );

	update_post_meta( $household_id, 'claimed_by', (int) $user_id );
	update_user_meta( $user_id, 'fcmc_household_id', (int) $household_id );

	if ( $h['paid_through'] ) {
		update_user_meta( $user_id, 'fcmc_paid_through_manual', $h['paid_through'] );
	}
	if ( $h['member_since'] ) {
		update_user_meta( $user_id, 'fcmc_member_since', $h['member_since'] );
	}

	// member2_* and cars are only ADOPTED when the user has nothing of their own —
	// never clobbering data a member already entered. This matters most on the
	// officer's Link control (fcmc-roster.php), which runs this same function
	// against ESTABLISHED accounts, not just fresh registrations. Overwriting a
	// real structured car list with the household's thin imported one (which by
	// design carries only car_model_year + car_description) would both destroy
	// member-entered data AND under-bill a multi-car household's renewal, since
	// the car count drives the dues quantity — see CRITICAL 3, 2026-09-11 review.
	foreach ( array( 'member2_name', 'member2_phone', 'member2_email' ) as $key ) {
		if ( $h[ $key ] && ! get_user_meta( $user_id, 'fcmc_' . $key, true ) ) {
			update_user_meta( $user_id, 'fcmc_' . $key, $h[ $key ] );
		}
	}
	$existing_cars = get_user_meta( $user_id, 'fcmc_car_profiles', true );
	if ( ! empty( $h['cars'] ) && empty( $existing_cars ) ) {
		update_user_meta( $user_id, 'fcmc_car_profiles', $h['cars'] );
	}

	if ( function_exists( 'fcmc_recompute_member' ) ) {
		fcmc_recompute_member( $user_id );
	}
}

/**
 * Mirror a claimed household's `paid_through` into its linked user's baseline
 * (`fcmc_paid_through_manual`) and recompute their status. No-op if the
 * household isn't claimed.
 *
 * This is the exact mirror-and-recompute logic fcmc_save_household_meta_box()
 * has always run on an officer's hand edit, extracted into one shared
 * function so the importer's update path (fcmc-import-roster.php — which
 * deliberately targets claimed households too) produces the identical effect
 * on the linked user. Before this existed, an import that changed a claimed
 * household's paid_through updated wp-admin but left the user's baseline (and
 * therefore the roster's status) stale — see CRITICAL 1, 2026-09-11 review.
 *
 * An explicit clear (empty paid_through) DELETES the user's baseline instead
 * of leaving the previous value in place, so a cleared household actually
 * lapses the member instead of silently surviving the next recompute — see
 * IMPORTANT 1 in the same review. NEVER writes `fcmc_paid_through` directly:
 * that key is a derived cache and a recompute with no orders behind it would
 * just wipe it back out.
 *
 * @param int $household_id Household post ID.
 * @return void
 */
function fcmc_household_sync_to_user( $household_id ) {
	$claimed_by = get_post_meta( $household_id, 'claimed_by', true );
	if ( ! $claimed_by ) {
		return;
	}

	$user_id      = (int) $claimed_by;
	$paid_through = get_post_meta( $household_id, 'paid_through', true );

	if ( $paid_through ) {
		update_user_meta( $user_id, 'fcmc_paid_through_manual', $paid_through );
	} else {
		delete_user_meta( $user_id, 'fcmc_paid_through_manual' );
	}

	if ( function_exists( 'fcmc_recompute_member' ) ) {
		fcmc_recompute_member( $user_id );
	}
}

/**
 * On registration, attach the new account to its household if the email matches.
 * No match is not an error — an officer links it from the roster instead.
 *
 * @param int $user_id New user ID.
 */
function fcmc_maybe_claim_household( $user_id ) {
	if ( get_user_meta( $user_id, 'fcmc_household_id', true ) ) {
		return;
	}
	$user = get_userdata( $user_id );
	if ( ! $user ) {
		return;
	}
	$household_id = fcmc_household_find_by_email( $user->user_email );
	if ( $household_id ) {
		fcmc_household_claim( $household_id, $user_id );
	}
}
add_action( 'user_register', 'fcmc_maybe_claim_household', 20 );
add_action( 'woocommerce_created_customer', 'fcmc_maybe_claim_household', 20 );

/* -------------------------------------------------------------------------
 * Officer edit screen — correct a household's membership date by hand
 * ---------------------------------------------------------------------- */

/**
 * Contact + membership fields exposed for hand-editing in wp-admin, and how each
 * one must be sanitised. Dates use the strict Y-m-d validator below; anything that
 * doesn't round-trip is rejected outright rather than stored as garbage — mirrors
 * the importer's $validate_ymd in fcmc-import-roster.php.
 *
 * @return array<string,string> field key => sanitiser kind: 'date' | 'email' | 'text'
 */
function fcmc_household_editable_fields() {
	return array(
		'paid_through'  => 'date',
		'member_since'  => 'date',
		'member1_name'  => 'text',
		'member1_phone' => 'text',
		'member1_email' => 'email',
		'member2_name'  => 'text',
		'member2_phone' => 'text',
		'member2_email' => 'email',
		'address'       => 'text',
		'city'          => 'text',
		'state'         => 'text',
		'zip'           => 'text',
	);
}

/**
 * Accept a date only if it round-trips through Y-m-d exactly — the same rule the
 * importer uses (fcmc-import-roster.php), so a hand-entry is held to the same
 * standard as the original CSV rather than trusting the browser's date input.
 *
 * @param string $raw Raw input.
 * @return string|null Canonical Y-m-d, or null if unusable.
 */
function fcmc_validate_ymd( $raw ) {
	$s = substr( trim( (string) $raw ), 0, 10 );
	$d = DateTimeImmutable::createFromFormat( 'Y-m-d', $s );
	if ( ! ( $d instanceof DateTimeImmutable ) || $d->format( 'Y-m-d' ) !== $s ) {
		return null;
	}
	return $s;
}

add_action(
	'add_meta_boxes',
	function () {
		add_meta_box(
			'fcmc_household_membership',
			__( 'Membership details', 'fcmc' ),
			'fcmc_render_household_meta_box',
			'fcmc_household',
			'normal',
			'high'
		);
	}
);

/**
 * The membership/contact fields meta box on the household edit screen.
 *
 * Gated on fcmc_manage_members independently of whatever capability got the
 * officer onto this screen — this is the box that touches the money-adjacent
 * paid_through field, so it checks for itself rather than trusting the screen.
 * Every value is member-supplied free text from a web form; escape on the way out
 * even though it is also sanitised on the way in.
 *
 * @param WP_Post $post Current post.
 */
function fcmc_render_household_meta_box( $post ) {
	if ( ! current_user_can( 'fcmc_manage_members' ) ) {
		echo '<p>' . esc_html__( 'You do not have permission to edit membership details.', 'fcmc' ) . '</p>';
		return;
	}

	$h = fcmc_household_get( $post->ID );
	wp_nonce_field( 'fcmc_household_save_' . $post->ID, 'fcmc_household_nonce' );

	$labels = array(
		'paid_through'  => __( 'Paid through', 'fcmc' ),
		'member_since'  => __( 'Member since', 'fcmc' ),
		'member1_name'  => __( 'Member 1 name', 'fcmc' ),
		'member1_phone' => __( 'Member 1 phone', 'fcmc' ),
		'member1_email' => __( 'Member 1 email', 'fcmc' ),
		'member2_name'  => __( 'Member 2 name', 'fcmc' ),
		'member2_phone' => __( 'Member 2 phone', 'fcmc' ),
		'member2_email' => __( 'Member 2 email', 'fcmc' ),
		'address'       => __( 'Address', 'fcmc' ),
		'city'          => __( 'City', 'fcmc' ),
		'state'         => __( 'State', 'fcmc' ),
		'zip'           => __( 'ZIP', 'fcmc' ),
	);
	?>
	<table class="form-table">
		<?php foreach ( fcmc_household_editable_fields() as $key => $kind ) : ?>
			<tr>
				<th scope="row">
					<label for="fcmc_<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $labels[ $key ] ); ?></label>
				</th>
				<td>
					<input
						type="<?php echo 'date' === $kind ? 'date' : ( 'email' === $kind ? 'email' : 'text' ); ?>"
						id="fcmc_<?php echo esc_attr( $key ); ?>"
						name="fcmc_<?php echo esc_attr( $key ); ?>"
						value="<?php echo esc_attr( $h[ $key ] ); ?>"
						class="regular-text"
					/>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
	<?php if ( $h['claimed_by'] ) : ?>
		<p><em><?php esc_html_e( 'This household is claimed by a user account. Saving "Paid through" here sets that account\'s baseline date and recomputes its status immediately.', 'fcmc' ); ?></em></p>
	<?php endif; ?>
	<?php
}

/**
 * Save the meta box.
 *
 * Verifies the nonce AND re-checks the capability here, independently of
 * whatever gate got the request this far — never trust the screen alone.
 *
 * @param int     $post_id Post ID.
 * @param WP_Post $post    Post object.
 */
function fcmc_save_household_meta_box( $post_id, $post ) {
	if ( ! $post || 'fcmc_household' !== $post->post_type ) {
		return;
	}
	if ( ! isset( $_POST['fcmc_household_nonce'] )
		|| ! wp_verify_nonce( sanitize_text_field( wp_unslash( $_POST['fcmc_household_nonce'] ) ), 'fcmc_household_save_' . $post_id )
	) {
		return;
	}
	if ( ! current_user_can( 'fcmc_manage_members' ) ) {
		return;
	}
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
		return;
	}

	foreach ( fcmc_household_editable_fields() as $key => $kind ) {
		$field = 'fcmc_' . $key;
		if ( ! isset( $_POST[ $field ] ) ) {
			continue;
		}
		$raw = wp_unslash( $_POST[ $field ] );

		if ( 'date' === $kind ) {
			$trimmed = trim( (string) $raw );
			if ( '' === $trimmed ) {
				update_post_meta( $post_id, $key, '' );
				continue;
			}
			$clean = fcmc_validate_ymd( $trimmed );
			if ( null === $clean ) {
				// Reject rather than store garbage — leave the existing value alone.
				continue;
			}
			update_post_meta( $post_id, $key, $clean );
		} elseif ( 'email' === $kind ) {
			update_post_meta( $post_id, $key, sanitize_email( $raw ) );
		} else {
			update_post_meta( $post_id, $key, sanitize_text_field( $raw ) );
		}
	}

	// If claimed, the officer's paid_through is the new BASELINE for the linked
	// user — mirror it and recompute via the shared helper (also used by the
	// importer's update path) so both write paths behave identically.
	fcmc_household_sync_to_user( $post_id );
}
add_action( 'save_post_fcmc_household', 'fcmc_save_household_meta_box', 10, 2 );
