<?php
/**
 * Plugin Name: FCMC Households
 * Description: The club's membership roster as records independent of WordPress user
 *              accounts. A household is one membership: up to two people and any number
 *              of cars. It exists whether or not anyone has registered on the site, which
 *              is what lets the 2026 roster be imported without creating 43 accounts
 *              nobody asked for. A user account attaches later, by email.
 *
 *              Capability type: its OWN ('fcmc_household' / 'fcmc_households'), not the
 *              default `post`, and NOT mapped onto `fcmc_manage_members`. That mapping was
 *              tried and reverted — see docs/superpowers/specs/2026-09-11-fcmc-roster-import/
 *              task-2-report.md. WordPress's _post_type_meta_capabilities() registers
 *              whatever string a post type maps `edit_post`/`read_post`/`delete_post` to as
 *              a META capability in the global $post_type_meta_caps array. Mapping those to
 *              `fcmc_manage_members` made WordPress believe THAT STRING was a meta
 *              capability, so every bare (no-post-ID) `current_user_can('fcmc_manage_members')`
 *              call got intercepted by map_meta_cap()'s default branch, re-mapped to
 *              `edit_post` with no post to check, and resolved to `do_not_allow` — silently
 *              breaking the officer-facing Club Roster tab, which gates on exactly that bare
 *              call. A post type's meta caps must never be mapped onto a standalone
 *              capability string used elsewhere as a plain gate.
 *
 *              `fcmc_manage_members` remains an ordinary, unmapped capability (see
 *              fcmc-roster.php); the primitives generated by `capability_type` below
 *              (edit_fcmc_households, delete_fcmc_households, etc.) are granted directly to
 *              `membership_officer` and `administrator` in fcmc_roster_install().
 *
 * @see docs/superpowers/specs/2026-09-10-fcmc-roster-import-design.md
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'init', function () {
	register_post_type( 'fcmc_household', array(
		'label'           => __( 'Households', 'fcmc' ),
		'public'          => false,          // never a front-end URL — this is member PII
		'show_ui'         => true,
		'show_in_menu'    => true,
		'menu_icon'       => 'dashicons-groups',
		'capability_type' => array( 'fcmc_household', 'fcmc_households' ),
		'capabilities'    => array( 'create_posts' => 'do_not_allow' ), // created by import or signup only
		'map_meta_cap'    => true,
		'supports'        => array( 'title' ),
		'show_in_rest'    => false,          // keep it off the public REST surface
	) );
} );

/**
 * Normalise an email for comparison. One rule, used everywhere.
 *
 * @param string $email Raw email.
 * @return string
 */
function fcmc_normalise_email( $email ) {
	return strtolower( trim( (string) $email ) );
}

/**
 * Find an UNCLAIMED household by either member's email.
 *
 * @param string $email Email to match.
 * @return int|null Post ID, or null.
 */
function fcmc_household_find_by_email( $email ) {
	$email = fcmc_normalise_email( $email );
	if ( '' === $email ) {
		return null;
	}

	foreach ( fcmc_household_all() as $id ) {
		if ( get_post_meta( $id, 'claimed_by', true ) ) {
			continue;
		}
		foreach ( array( 'member1_email', 'member2_email' ) as $key ) {
			if ( fcmc_normalise_email( get_post_meta( $id, $key, true ) ) === $email ) {
				return (int) $id;
			}
		}
	}

	return null;
}

/**
 * All household IDs. ~48 records, so a plain query is fine.
 *
 * @param array $args Extra WP_Query args.
 * @return int[]
 */
function fcmc_household_all( $args = array() ) {
	return get_posts( array_merge( array(
		'post_type'      => 'fcmc_household',
		'post_status'    => 'publish',
		'posts_per_page' => -1,
		'fields'         => 'ids',
		'orderby'        => 'title',
		'order'          => 'ASC',
	), $args ) );
}

/**
 * A household as a flat array, with every meta key present.
 *
 * @param int $id Post ID.
 * @return array
 */
function fcmc_household_get( $id ) {
	$keys = array(
		'member1_name', 'member1_phone', 'member1_email',
		'member2_name', 'member2_phone', 'member2_email',
		'address', 'city', 'state', 'zip',
		'cars', 'paid_through', 'member_since',
		'fcmc_source', 'claimed_by', 'import_batch',
	);

	$out = array( 'id' => (int) $id );
	foreach ( $keys as $key ) {
		$out[ $key ] = get_post_meta( $id, $key, true );
	}
	$out['cars'] = is_array( $out['cars'] ) ? $out['cars'] : array();

	return $out;
}

/**
 * Attach a user account to a household and adopt its membership facts.
 *
 * The imported date lands in fcmc_paid_through_manual — the BASELINE, not the
 * effective date — so recompute treats it as a floor and can never wipe it.
 *
 * @param int $household_id Household post ID.
 * @param int $user_id      User ID.
 */
function fcmc_household_claim( $household_id, $user_id ) {
	$h = fcmc_household_get( $household_id );

	update_post_meta( $household_id, 'claimed_by', (int) $user_id );
	update_user_meta( $user_id, 'fcmc_household_id', (int) $household_id );

	if ( $h['paid_through'] ) {
		update_user_meta( $user_id, 'fcmc_paid_through_manual', $h['paid_through'] );
	}
	if ( $h['member_since'] ) {
		update_user_meta( $user_id, 'fcmc_member_since', $h['member_since'] );
	}
	foreach ( array( 'member2_name', 'member2_phone', 'member2_email' ) as $key ) {
		if ( $h[ $key ] ) {
			update_user_meta( $user_id, 'fcmc_' . $key, $h[ $key ] );
		}
	}
	if ( ! empty( $h['cars'] ) ) {
		update_user_meta( $user_id, 'fcmc_car_profiles', $h['cars'] );
	}

	if ( function_exists( 'fcmc_recompute_member' ) ) {
		fcmc_recompute_member( $user_id );
	}
}

/**
 * On registration, attach the new account to its household if the email matches.
 * No match is not an error — an officer links it from the roster instead.
 *
 * @param int $user_id New user ID.
 */
function fcmc_maybe_claim_household( $user_id ) {
	if ( get_user_meta( $user_id, 'fcmc_household_id', true ) ) {
		return;
	}
	$user = get_userdata( $user_id );
	if ( ! $user ) {
		return;
	}
	$household_id = fcmc_household_find_by_email( $user->user_email );
	if ( $household_id ) {
		fcmc_household_claim( $household_id, $user_id );
	}
}
add_action( 'user_register', 'fcmc_maybe_claim_household', 20 );
add_action( 'woocommerce_created_customer', 'fcmc_maybe_claim_household', 20 );
